<?php
require_once "config/database.php"; require_once "includes/functions.php";
if(empty($_SESSION['delivery_id'])){header('Location: delivery.php');exit;}
$id=(int)$_SESSION['delivery_id']; $error='';
$s=$conn->prepare("SELECT id,name,email,phone,address,password,status FROM delivery_staff WHERE id=? LIMIT 1");$s->bind_param('i',$id);$s->execute();$staff=$s->get_result()->fetch_assoc();
if(!$staff){unset($_SESSION['delivery_id'],$_SESSION['delivery_name']);header('Location: delivery.php');exit;}
if($_SERVER['REQUEST_METHOD']==='POST'){
 $action=$_POST['action']??'';
 if($action==='profile'){$name=trim($_POST['name']??'');$email=trim($_POST['email']??'');$phone=trim($_POST['phone']??'');$address=trim($_POST['address']??'');$c=$conn->prepare("SELECT id FROM delivery_staff WHERE email=? AND id<>? LIMIT 1");$c->bind_param('si',$email,$id);$c->execute();if($name===''||!filter_var($email,FILTER_VALIDATE_EMAIL))$error='Enter a valid name and email.';elseif($c->get_result()->num_rows)$error='That email is already in use.';else{$u=$conn->prepare("UPDATE delivery_staff SET name=?,email=?,phone=?,address=? WHERE id=?");$u->bind_param('ssssi',$name,$email,$phone,$address,$id);$u->execute();$_SESSION['delivery_name']=$name;flash('success','Delivery profile updated.');header('Location: delivery_profile.php');exit;}}
 elseif($action==='password'){$cur=$_POST['current_password']??'';$new=$_POST['new_password']??'';$con=$_POST['confirm_password']??'';if(!password_verify($cur,$staff['password']))$error='Current password is incorrect.';elseif(strlen($new)<6||$new!==$con)$error='Check the new password fields.';else{$h=password_hash($new,PASSWORD_DEFAULT);$u=$conn->prepare("UPDATE delivery_staff SET password=? WHERE id=?");$u->bind_param('si',$h,$id);$u->execute();flash('success','Password changed successfully.');header('Location: delivery_profile.php');exit;}}
}
?><!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Delivery Account | Ice Cream Delights</title><link rel="stylesheet" href="css/style.css"></head><body class="delivery-body"><header class="delivery-top"><div class="brand"><span class="brand-cone">🍦</span><span><b>ICE CREAM</b><b>DELIGHTS</b></span></div><div><a class="btn btn-light" href="delivery.php">Dashboard</a><a class="btn" href="delivery.php?logout=1">Logout</a></div></header><main class="delivery-main"><section class="delivery-welcome"><div><p class="eyebrow">Account Management</p><h1>My Delivery Account</h1><p>Manage your profile and password.</p></div><div class="delivery-badge">👤<span><?=e($staff['name'])?></span></div></section><?php if($error):?><div class="form-error"><?=e($error)?></div><?php endif;?><section class="account-grid"><div class="form-card account-card"><div class="auth-icon">👤</div><h2>Profile Information</h2><form method="post"><input type="hidden" name="action" value="profile"><label>Full Name</label><input name="name" value="<?=e($staff['name'])?>" required><label>Email</label><input type="email" name="email" value="<?=e($staff['email'])?>" required><label>Phone</label><input name="phone" value="<?=e($staff['phone'])?>"><label>Address</label><textarea name="address" rows="4"><?=e($staff['address']??'')?></textarea><button class="btn" type="submit">Save Profile</button></form></div><div class="form-card account-card"><div class="auth-icon">🔐</div><h2>Change Password</h2><form method="post"><input type="hidden" name="action" value="password"><label>Current Password</label><input type="password" name="current_password" required><label>New Password</label><input type="password" name="new_password" minlength="6" required><label>Confirm New Password</label><input type="password" name="confirm_password" minlength="6" required><button class="btn" type="submit">Change Password</button></form></div></section></main></body></html>
